### ISSUE TITLE
End Points not Found

### ISSUE THREAD

**Issue by JessJessop** [IBM-Cloud/bluemix-cli-release#11]
Greetings,

The download and install went slick, But the login returns End Points not Available

Thanks

**Comment by boyang9527** [comment]
can you paste how you login and the message output here?

**Comment by JessJessop** [comment]
![bli](https://user-images.githubusercontent.com/18367758/32253975-3520ae30-be5b-11e7-8916-dcb2328b93f4.JPG)

**Comment by boyang9527** [comment]
looks like you have DNS look up issue for mccp.ng.bluemix.net 

can you ping or curl mccp.ng.bluemix.net ?

**Comment by archerzz** [comment]
@JessJessop Is `bx login` back to normal?

**Comment by JessJessop** [comment]
Yes, sorry for the late reply. I don't know what the problem was but it went away the same day it started.

Thank You

Jess


________________________________
