### ISSUE TITLE
Install from shell fails `/tmp/Bluemix_CLI/install: not found`

### ISSUE THREAD

**Issue by makandre** [IBM-Cloud/bluemix-cli-release#14]
On Linux, using the command `curl -fsSL https://clis.ng.bluemix.net/install/linux | sh` to install.

The command used to work but started to fail recently with:

```sh
Bluemix_CLI/install_bluemix_cli
chmod: cannot access ‘/tmp/Bluemix_CLI/install’: No such file or directory
sh: 67: /tmp/Bluemix_CLI/install: not found
Install failed.
```

**Comment by hmckinne** [comment]
The contents of the tar file changed, but the shell script was not changed accordingly. Can someone please fix this?

**Comment by neumannrf** [comment]
@makandre @hmckinne In the meantime, try 
```Shell
curl -fsSL https://clis.ng.bluemix.net/install/linux | sed 's/\/install/\/install_bluemix_cli/g' | sh
```

**Comment by neumannrf** [comment]
@boyang9527 Please note that, even after replacing `install` by `install_bluemix_cli` with the `sed` command above, I still had to invoke `sudo`, otherwise I'd still run into an installation error.

**Comment by neumannrf** [comment]
The automatic `sudo`-ing part is still not working...

**Comment by boyang9527** [comment]
thanks @neumannrf @makandre  it should be fixed.
